playlists = [
    # genres
    {"name": "gc | african", "id": "PL4xpJlmNQtFob3k85b9DVLYBA6rD9CrVS"},
    {"name": "gc | bachata", "id": "PL4xpJlmNQtFquh8apCSAxGBprZv21Vijk"},
    {"name": "gc | country", "id": "PL4xpJlmNQtFqjV1GrkM6xpzZ5UOzxG4Sq"},
    {"name": "gc | culture", "id": "PL4xpJlmNQtFoyerS9l1cpekZ0ah87R3zk"},
    {"name": "gc | cumbia", "id": "PL4xpJlmNQtFqbKnyWoudcIQQuhEUcV4Qm"},
    {"name": "gc | funk", "id": "PL4xpJlmNQtFo0stL7_zgn9x33DGVWmlko"},
    {"name": "gc | indian", "id": "PL4xpJlmNQtFpk5hSCtHaY6o6k-y-sTYA1"},
    {"name": "gc | jazz", "id": "PL4xpJlmNQtFr1-5lm_TOTtr2Qs4u86lr9"},
    {"name": "gc | latin", "id": "PL4xpJlmNQtFrhJd4zhdSKfID3ZkBcNpwx"},
    {"name": "gc | merengue", "id": "PL4xpJlmNQtFrXIh1BFsL3UIob-ym_FNcj"},
    {"name": "gc | salsa", "id": "PL4xpJlmNQtFrQCiLyZsAEvIbx1OyS9bgP"},
    {"name": "gc | trippy", "id": "PL4xpJlmNQtFpLeGggg2rozLP0YnXKZLDZ"},
    {"name": "hd | dancehall", "id": "PL4xpJlmNQtFrkoJrpZaRTb3vIORFA9V2-"},
    {"name": "hd | deep", "id": "PL4xpJlmNQtFpsHPbLQK6QYSDj_EQkOmic"},
    {"name": "hd | dembow", "id": "PL4xpJlmNQtFoRAXv2pWAn6lKh2B4nQfDl"},
    {"name": "hd | dnb", "id": "PL4xpJlmNQtFpSGDKoP4heY9OriZuzQoLo"},
    {"name": "hd | edm", "id": "PL4xpJlmNQtFrRyR1F52x2oLgFTsvLEH3M"},
    {"name": "hd | eurodance", "id": "PL4xpJlmNQtFqrDi7ym32tgQf1Ut5_eAAY"},
    {"name": "hd | house", "id": "PL4xpJlmNQtFocm9Wy6zj-dGu98Nm560lq"},
    {"name": "hd | reggaeton", "id": "PL4xpJlmNQtFrcpkpadJLUQrar9LuQgXtP"},
    {"name": "hd | techno", "id": "PL4xpJlmNQtFoyjmHYJzv3WozV3zi88HEG"},
    {"name": "ue | ambient", "id": "PL4xpJlmNQtFrNEBv6kt2IQMWxGl2rmP6I"},
    {"name": "ue | electric", "id": "PL4xpJlmNQtFq2-wk85MLBdFmvfQwyqSZz"},
    {"name": "wc | cool", "id": "PL4xpJlmNQtFod5uq452L4MD_vGFoEQuFT"},
    {"name": "wc | ballad", "id": "PL4xpJlmNQtFpaQ6TDa74dsM73f-nHa0Zt"},
    {"name": "wc | chillhop", "id": "PL4xpJlmNQtFoCx4NUyRAdXEvEoAiFsDKD"},
    {"name": "wc | electro pop", "id": "PL4xpJlmNQtFqlJ02iP6JkTyTucRW0gqkM"},
    {"name": "wc | rnb", "id": "PL4xpJlmNQtFqFX1GIdej4QyI9NHcrM8Ev"},
    {"name": "wc | roots dub", "id": "PL4xpJlmNQtFqTylKy0nL6RKP469zA4R6v"},
    {"name": "x | alt", "id": "PL4xpJlmNQtFpNYPZnuQsgNtfNPU6mPG6j"},
    {"name": "x | hiphop", "id": "PL4xpJlmNQtFrcjjKlPTjDMuD7QQuoY1Ue"},
    {"name": "x | phonk", "id": "PL4xpJlmNQtFqpWGL-OApxT_ruOdybzoTb"},
    {"name": "x | pop", "id": "PL4xpJlmNQtFonC2Eq96pBBB-lSCnBX_FP"},
    # sets
    {"name": "set | matrix", "id": "PL4xpJlmNQtFpODcchd7IdefVZcxu17193"},
    {"name": "set | wedding", "id": "PL4xpJlmNQtFr2yGDABdc0PZ03RFSGRZPR"},
    {"name": "set | dreams", "id": "PL4xpJlmNQtFqaFJtnwRmcLBMJWpT8PZDf"},
    {"name": "set | amanecer", "id": "PL4xpJlmNQtFpBatkqK4rb_YrBLpCd-Tv9"},
]